### ISSUE TITLE
Link aus dem `@target` im XML ändert sich auf der DTA-Seite

### ISSUE THREAD

**Issue by cthomasdta** [mprell/reisetagebuch-heinrichxi#2]
aus der `//editorialDecl`:

```XML
Abweichungen der <ref target="https://nbn-resolving.org/urn:nbn:de:urmel-hisbest-235636">zeitgenössische Abschrift</ref> vom originalen Autographen
```

Der Link zu `https://nbn-resolving.org/urn:nbn:de:urmel-hisbest-235636` wird [auf der DTA-Seite](https://www.deutschestextarchiv.de/geusau_reisetagebuchHeinrichxiReuss_1740) im Bereich "Weitere Informationen", wo dieser Text zu stehen kommt, zu `https://www.deutschestextarchiv.de/` :

![image](https://github.com/user-attachments/assets/945efac0-6e42-4524-951c-bdd984bfd761)

Sehr merkwürdig, kann ich auch im HTML der DTA-Seite der Seite nicht nachvollziehen. @haoess verstehst du das?

---

P.S./NB: der Tippfehler "zeitgenössische Abschrift" = "zeitgenössischen Abschrift" ist schon anderweitig gemeldet.

**Comment by haoess** [comment]
Fehler meinerseits, Verlinkung nun korrekt.

**Comment by mprell** [comment]
Danke!
